// Book search
export const BOOKS_SEARCH_REQUESTED = "BOOKS_SEARCH_REQUESTED";
export const BOOKS_SEARCH_RESOLVED = "BOOKS_SEARCH_RESOLVED";

// List Items
export const GET_LISTITEMS_REQUESTED = "GET_LISTITEMS_REQUESTED";
export const GET_LISTITEMS_RESOLVED = "GET_LISTITEMS_RESOLVED";
